Repository axodotdev/oranda, pull requests merged in 2023-01, with the labels that each got.

#64 run cargo dist init --ci=github --installer=github-shell --installer=github-powershell
  .github/workflows/release.yml
  Cargo.toml
Labels: status - work in progress

#94 allow prefix in oranda serve
  Cargo.lock
  Cargo.toml
  src/commands/serve.rs
  src/site/header.rs
  src/site/mod.rs
Labels: status - ready for review

#76 Merge css options & use axo asset
  Cargo.lock
  Cargo.toml
  src/config/mod.rs
  src/config/oranda.rs
  src/config/project/javascript.rs
  src/config/project/rust.rs
  src/errors.rs
  src/main.rs
  src/site/css/mod.rs
  src/site/html.rs
  src/site/mod.rs
  src/tests/mod.rs
Labels: status - changes requested

#101 [WIP] doc(readme): add content to readme
  .github/workflows/web.yml
  README.md
Labels: status - work in progress

#103 feat(tests): split main/lib, tests to top level
  src/commands/build.rs
  src/commands/serve.rs
  src/config/mod.rs
  src/config/project/javascript.rs
  src/config/project/mod.rs
  src/config/project/rust.rs
  src/lib.rs
  src/main.rs
  src/tests/mod.rs
  tests/mod.rs
Labels: status - ready for review

#109 fix(css): if path prefix, serve css from prefix
  src/site/css/mod.rs
Labels: status - ready for review

#108 feat(message): add stdout and logging
  .gitignore
  Cargo.lock
  Cargo.toml
  src/commands/build.rs
  src/commands/serve.rs
  src/config/oranda.rs
  src/config/project/mod.rs
  src/errors.rs
  src/lib.rs
  src/main.rs
  src/message.rs
Labels: status - work in progress

#99 Add support for cargo dist
  Cargo.lock
  Cargo.toml
  dev/oranda.json
  oranda.json
  src/config/artifacts.rs
  src/config/mod.rs
  src/config/oranda.rs
  src/config/project/mod.rs
  src/errors.rs
  src/site/artifacts.rs
  src/site/header.rs
  src/site/html.rs
  src/site/javascript/detect_os.js
  src/site/mod.rs
Labels: status - work in progress

#145 more reorg
  src/site/layout/css.rs
  src/site/layout/footer.rs
  src/site/layout/head.rs
  src/site/layout/header.rs
  src/site/layout/javascript/detect_os.rs
  src/site/layout/javascript/mod.rs
  src/site/layout/mod.rs
  src/site/mod.rs
Labels: status - ready for review
